### ISSUE TITLE
lightweight alternative (shameless advertisment)

### ISSUE THREAD

**Issue by milahu** [NimitzDEV/logical-expression-parser#2]
https://github.com/milahu/logic_fn
can solve the same problem with 4 times less code : )

started as fork, ended as full rewrite
github only tracks forks, so this is my attempt to link my similar project

**Comment by NimitzDEV** [comment]
Okay, thanks. I think the main difference between these two libs is the approach method. **logical-expression-parser** will go through stages like tokenizing, AST building, and utilize Reverse Polish Notation to safely parse the express, and gives more chance for developers to take part in the process and change things accordingly.
